### PR TITLE
User Interface:  OOP User interface project for the Tic Tac Toe Game

### PR DESCRIPTION
**Pull request by t-yanick**
This is the second collaborative project from the Ruby module on Object-Oriented Programming from the Microverse program, It's a Tic Tac Toe game with User Interface. Please review and give feedback to enhance our learning.

Thanks

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### Hi @t-yanick and @bmuhamood :clap: :clap:
#### You have done a good job :muscle: however, you need to implement the following :point_down:  requirement before the project can be approved

- **_There is a lot of duplicate files in your project, please remove them._**

- **_Give a descriptive name to the Pull Request title._**

#### _Reviewed by Temitayo Adeleke._

**Comment by bmuhamood** [comment]
Milestone 2: Implementing the requested changes in the project. 

- Removed all the duplicate files from the interface branch
- Added all the required files to the root and other respective directories
- Linters working fine
- Fixed grammar issues in the Readme file.

**Comment by bmuhamood** [comment]
User Interface: Implementing the requested changes in the project. 

- Updated the pull request from milestone to User Interface as it's the current project are working on.

**Review by kitpao — APPROVED** [review]
# 👋 Hello @t-yanick and @bmuhamood 

🌟 It is great that you are considering the case when the user wants to play again and all your validations 🏅  I see that you already defined your code, it was not necessary for this milestone, but you have your flow defined as requested so, it is ok 💯  In the review for next milestone, you are going to have the functionality of your code reviewed 📝 The readme was also not required yet, but nice to see you did it, it will be reviewed in the last milestone

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

### 👏 Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Comment by bmuhamood** [comment]
Thanks a lot Kitpao. Noted all the information.

**Pull request merged**
